"""Spawn one Clearpath ground vehicle into the running simulation world.

Included by simulation_matrix.launch.py; it never starts its own world or
clock. The robot description and controller parameters are generated at image
build time for the requested robot (jackal_j100 or husky_a200).

Command chain (verified: the gz_ros2_control plugin consumes ROS
/platform/cmd_vel directly):

  /cmd_vel/nav -> greenhouse_cmd_gate -> /cmd_vel -> greenhouse_sim_cmd_sink
      -> /platform/cmd_vel -> platform_velocity_controller -> wheels

The gate itself belongs to the navigation assembly (closed_loop.launch.py
starts it with source /cmd_vel/nav and the simulation qualification scope);
this launch provides the sink so the chain reaches the platform controller.
The generated cmd_vel bridge is deliberately NOT included: its gz->ROS
direction would publish on /cmd_vel and compete with the gate.

Sensors (VLP16 lidar, IMU, RGB-D camera) are bridged to the stack topic names
by the per-robot sensor-bridge config. FAST-LIO owns odom -> base_link;
the robot state publisher owns platform and sensor transforms.
"""
from pathlib import Path
import json
import subprocess
from xml.etree import ElementTree as ET
import yaml

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription,
                            OpaqueFunction, RegisterEventHandler)
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def instrument_robot(setup_path, output, world_name):
    """Add contact sensors after Gazebo's normal URDF conversion.

    Geometry, inertial properties, joints and controller plugins stay as
    generated by Clearpath. Instrumentation observes each existing collision.
    """
    output.mkdir(parents=True, exist_ok=True)
    urdf = subprocess.run([
        'xacro', str(setup_path / 'robot.urdf.xacro'), 'is_sim:=true',
        f'gazebo_controllers:={setup_path}/platform/config/control.yaml',
        'namespace:=/', 'use_fake_hardware:=false',
        'use_manipulation_controllers:=false', 'use_platform_controllers:=true'],
        check=True, capture_output=True, text=True).stdout
    urdf_path = output / 'robot.urdf'
    urdf_path.write_text(urdf)
    sdf = subprocess.run(['gz', 'sdf', '-p', str(urdf_path)],
                         check=True, capture_output=True, text=True).stdout
    root = ET.fromstring(sdf)
    bridges, wheel_collisions = [], []
    for link in root.find('model').findall('link'):
        for collision in link.findall('collision'):
            index = len(bridges)
            # Harmonic's Contact system publishes at the scoped sensor path.
            topic = (f'/world/{world_name}/model/robot/link/{link.get("name")}'
                     f'/sensor/simulation_contact_{index}/contact')
            sensor = ET.SubElement(link, 'sensor',
                                   {'name': f'simulation_contact_{index}', 'type': 'contact'})
            ET.SubElement(sensor, 'always_on').text = 'true'
            ET.SubElement(sensor, 'update_rate').text = '20'
            ET.SubElement(sensor, 'topic').text = topic
            contact = ET.SubElement(sensor, 'contact')
            ET.SubElement(contact, 'collision').text = collision.get('name')
            bridges.append({'gz_topic_name': topic, 'ros_topic_name': '/simulation/contacts',
                            'gz_type_name': 'gz.msgs.Contacts',
                            'ros_type_name': 'ros_gz_interfaces/msg/Contacts',
                            'direction': 'GZ_TO_ROS'})
            if 'wheel' in link.get('name'):
                wheel_collisions.append(collision.get('name'))
    destination = output / 'robot-instrumented.sdf'
    ET.ElementTree(root).write(destination, encoding='utf-8', xml_declaration=True)
    bridge_path = output / 'contact-bridge.yaml'
    bridge_path.write_text(yaml.safe_dump(bridges))
    (output / 'contact-instrumentation.json').write_text(json.dumps({
        'wheel_collision_names': wheel_collisions, 'sensor_count': len(bridges)}, indent=2))
    return destination, bridge_path


def setup(context):
    robot = LaunchConfiguration('robot').perform(context)
    world_name = LaunchConfiguration('world_name').perform(context)
    spawn_x = LaunchConfiguration('spawn_x').perform(context)
    spawn_y = LaunchConfiguration('spawn_y').perform(context)
    spawn_z = LaunchConfiguration('spawn_z').perform(context)
    setup_path = Path(f'/opt/greenhouse_sim/robot/{robot}')
    share = Path(get_package_share_directory('greenhouse_nav2_bringup'))
    output = Path(LaunchConfiguration('output').perform(context))
    robot_sdf, contacts_config = instrument_robot(setup_path, output, world_name)

    description = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(str(
            Path(get_package_share_directory('clearpath_platform_description'))
            / 'launch' / 'description.launch.py')),
        launch_arguments={
            'setup_path': str(setup_path),
            'use_sim_time': 'true',
            'namespace': '/',
            'use_fake_hardware': 'false',
            'use_manipulation_controllers': 'false',
            'use_platform_controllers': 'true',
        }.items())

    joint_state_spawner = Node(
        package='controller_manager', executable='spawner',
        name='spawner_joint_state_broadcaster',
        arguments=['--controller-manager-timeout', '120', '--switch-timeout', '120',
                   '--service-call-timeout', '120', 'joint_state_broadcaster'],
        additional_env={'ROS_SUPER_CLIENT': 'True'}, output='screen')
    velocity_spawner = Node(
        package='controller_manager', executable='spawner',
        name='spawner_platform_velocity_controller',
        arguments=['--controller-manager-timeout', '120', '--switch-timeout', '120',
                   '--service-call-timeout', '120', 'platform_velocity_controller'],
        additional_env={'ROS_SUPER_CLIENT': 'True'}, output='screen')

    # Large RGB-D transfers accumulated seconds of IMU backlog in a shared
    # bridge. Give IMU, lidar and camera independent processes; camera
    # bridging starts only when ROS has a subscriber. Sensor rates, values,
    # timestamps and topic names remain those of the physical simulation.
    config = share / 'config' / 'simulation' / (
        f'sensor-bridge-{"j100" if robot == "jackal_j100" else "a200"}.yaml')
    groups = {'imu': [], 'lidar': [], 'camera': []}
    for entry in yaml.safe_load(config.read_text()):
        if entry['ros_type_name'] == 'sensor_msgs/msg/Imu':
            group = 'imu'
        elif entry['ros_topic_name'].startswith('/sensors/camera/'):
            group = 'camera'
            entry['lazy'] = True
        else:
            group = 'lidar'
        groups[group].append(entry)
    sensor_bridges = []
    for group, entries in groups.items():
        bridge_config = output / f'sensor-bridge-{group}.yaml'
        bridge_config.write_text(yaml.safe_dump(entries))
        sensor_bridges.append(Node(
            package='ros_gz_bridge', executable='parameter_bridge',
            name='simulation_sensor_bridge' if group == 'imu' else f'simulation_{group}_bridge',
            # config_file and CLI topic arguments must not be mixed.
            parameters=[{'use_sim_time': True, 'config_file': str(bridge_config)}],
            output='screen'))

    # Command sink: the unique /cmd_vel consumer, converting the gate output
    # to the platform controller input.
    command_sink = Node(
        package='greenhouse_cmd_gate', executable='greenhouse_cmd_sink',
        name='greenhouse_sim_cmd_sink',
        parameters=[
            str(share / 'config' / 'simulation' / 'command-gate.yaml'),
            {'use_sim_time': True}],
        output='screen')

    create_robot = Node(
        package='ros_gz_sim', executable='create', name=f'create_{robot}',
        arguments=['-name', 'robot', '-world', world_name,
                   '-x', spawn_x, '-y', spawn_y, '-z', spawn_z, '-Y', '0.0',
                   '-file', str(robot_sdf)],
        output='screen')

    actions = [description, joint_state_spawner, velocity_spawner,
               *sensor_bridges, command_sink, create_robot]
    actions.append(Node(package='ros_gz_bridge', executable='parameter_bridge',
                        name='simulation_contact_bridge',
                        parameters=[{'use_sim_time': True, 'config_file': str(contacts_config)}],
                        output='screen'))
    actions.append(Node(package='greenhouse_nav2_bringup', executable='simulation_lidar_filter.py',
                        parameters=[{'use_sim_time': True}], output='screen'))
    if LaunchConfiguration('navigation').perform(context) == 'true':
        controller = LaunchConfiguration('controller').perform(context)
        deployment = yaml.safe_load((share / 'config' / 'simulation' /
                                     f'deployment-{robot}.yaml').read_text())
        deployment['controllers'] = [controller]
        output.mkdir(parents=True, exist_ok=True)
        deployment_path = output / f'deployment-{robot}-{controller}.yaml'
        deployment_path.write_text(yaml.safe_dump(deployment))
        navigation = IncludeLaunchDescription(
            PythonLaunchDescriptionSource(str(share / 'launch' / 'closed_loop.launch.py')),
            launch_arguments={'deployment': str(deployment_path)}.items())
        startup = Node(package='greenhouse_nav2_bringup', executable='simulation_ground_startup.py',
                       parameters=[{'use_sim_time': True, 'output': str(output/'ground-startup.json')}],
                       output='screen')
        def start_navigation(event, context):
            if event.returncode != 0:
                raise RuntimeError('Ground vehicle did not physically settle; navigation startup refused')
            return [navigation]
        actions.extend([RegisterEventHandler(OnProcessExit(target_action=startup,
                           on_exit=start_navigation)), startup])
    return actions


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('robot', description='jackal_j100 or husky_a200'),
        DeclareLaunchArgument('world_name', description='gz world name for spawning'),
        DeclareLaunchArgument('world', default_value=''),
        DeclareLaunchArgument('spawn_x', default_value='0.0'),
        DeclareLaunchArgument('spawn_y', default_value='0.0'),
        DeclareLaunchArgument('spawn_z', default_value='0.3'),
        DeclareLaunchArgument('task', default_value='site_default'),
        DeclareLaunchArgument('output', default_value='/tmp/simulation'),
        DeclareLaunchArgument('navigation', default_value='true', choices=['true', 'false']),
        DeclareLaunchArgument('controller', default_value='mppi', choices=['mppi', 'cmu']),
        OpaqueFunction(function=setup),
    ])
